use bevy::math::DVec3;

use crate::constants;

#[derive(Debug)]
/// A force generator for Gravity.
pub struct Gravity {
    g: DVec3,
}

impl Gravity {
    /// Creates a new gravity force generator with the given value for g.
    pub fn new(g: DVec3) -> Self {
        Self { g }
    }

    /// Returns the force currently generated by gravity on the given mass.
    pub fn force(&self, m: f64) -> DVec3 {
        m * self.g
    }
}

impl Default for Gravity {
    fn default() -> Self {
        Self {
            g: *constants::DEFAULT_GRAVITY,
        }
    }
}
